[lint]
# Add "Q" to the list of enabled codes.
select = ["E4", "E7", "E9", "F", "Q", "N"]
ignore = ["N802", "Q000"]
preview = true

#[format]
#quote-style = "double"


# [lint.flake8-quotes]
# docstring-quotes = "double"